const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const stored={};const sent=[],navigated=[];
const chrome={storage:{session:{get:async key=>({[key]:stored[key]}),set:async values=>Object.assign(stored,values),remove:async key=>{for(const item of Array.isArray(key)?key:[key])delete stored[item];}}},tabs:{sendMessage:async(...args)=>{sent.push(args);return {received:true};},update:async(...args)=>{navigated.push(args);return {};}}};
const context={chrome,URL,Date,Error};vm.createContext(context);
vm.runInContext(fs.readFileSync('background/pearson-course.js','utf8'),context);
const ui=fs.readFileSync('content-scripts/pearson-course.js','utf8');
const shell=fs.readFileSync('content-scripts/pearson-course-shell.js','utf8');
const help=fs.readFileSync('popup/help.html','utf8');
const tour=fs.readFileSync('sidepanel/tour.js','utf8');
const manifest=JSON.parse(fs.readFileSync('manifest.json','utf8'));
const eligibility=ui.match(/  const eligible=text=>[^;]+;/)?.[0];
assert(eligibility,'the assignment-list eligibility rule is present');
assert.match(ui,/async function readScore\(entry\)/,'the queue reads Pearson’s score before opening an assignment');
assert.match(ui,/score===0\)assignments\.push/,'only assignments with an explicitly confirmed zero score enter the queue');
assert.match(ui,/\^Start\$\/i\.test\(clean\(e\.textContent\)\)/,'the queue can enter an eligible assignment through Pearson Start');
assert.match(ui,/const resume=controls\.some\(e=>\/\^Resume\$\/i\.test\(clean\(e\.textContent\)\)\)/,'a Pearson Resume action is detected as already started');
assert.match(ui,/const canStart=!!start\|\|\(!resume&&!!firstQuestion\)/,'a zero-score item without Resume can use its first question link');
assert.match(ui,/else if\(!resume&&firstQuestion\)\{status\('Opening the first question in this not-started assignment…'\);firstQuestion\.click\(\);\}/,'the first-question fallback clicks Pearson’s native question link');
assert.match(ui,/Already has a score/,'assignments with a score are retained in the review summary');
assert.match(ui,/Media still to review/,'the final dialog lists pending media separately from unanswered questions');
assert.match(fs.readFileSync('background/pearson-course.js','utf8'),/Pearson may update credit after the media route returns, even if its tab is blank\. Verify its status\./,'pending media review carries the Pearson-return advisory');
assert.match(ui,/const embeddedList=list&&window\.top!==window/,'the iframe detects when Pearson hosts its assignment list inside the course shell');
assert.match(ui,/event\.source!==window\.parent/,'the iframe accepts course-mode actions only from its parent shell');
assert.match(ui,/type:'review',questions,assignments/,'skipped-work details are forwarded to the top-level course shell');
assert.match(shell,/position:fixed!important/,'the course-mode launcher is pinned to the visible top-level viewport');
assert.match(shell,/aria-expanded="false"/,'the course-mode launcher starts collapsed to keep the assignment list clear');
assert.match(shell,/reviewAssignment/,'the top-level review dialog can reopen an assignment with pending media');
assert.match(ui,/type==='reviewAssignment'/,'the assignment iframe handles user-requested media-review navigation');
assert(manifest.content_scripts.some(script=>script.js?.includes('content-scripts/pearson-course-shell.js')&&script.matches?.includes('https://mylabmastering.pearson.com/courses/*/menu/*')),'the top-level Pearson course shell loads the pinned launcher');
const parseScoreSource=ui.match(/  function parseScore\(text\)\{[^}]+\}/)?.[0];
assert(parseScoreSource,'the Pearson score parser is present');
const parseScore=vm.runInNewContext(parseScoreSource+'\nparseScore',{Number,String,RegExp});
assert.equal(parseScore('0%'),0);
assert.equal(parseScore('see score for Lesson Section 6.3 79.37%'),79.37,'scores appended to Pearson’s existing link text are recognized');
assert.equal(parseScore('see score'),null,'unknown scores stay out of the automatic queue');
assert.match(help,/<section id="full-course-mode">/,'the Help guide explains Pearson Full Course Mode');
assert.match(help,/Continue without review pauses/,'the guide documents the optional review-pause setting');
assert.match(tour,/title:'11\. Pearson course mode'/,'the walkthrough has a Pearson course-mode step');
assert.match(tour,/target:'#full-course-mode'/,'the walkthrough highlights the matching course-mode guide section');
const eligible=vm.runInNewContext(eligibility+'\neligible',{String});
assert.equal(eligible('HW Section1.1-1.6 Introduction'),true);
assert.equal(eligible('Lesson Section 6.3 Small Sample Confidence Intervals'),true);
assert.equal(eligible('Practice Exam #1'),false);
assert.equal(eligible('Exam #1'),false);
const call=(message,sender)=>context.pearsonCourseMessage(message,sender);
const list={url:'https://mylab.pearson.com/Student/DoAssignments.aspx',tab:{id:10},frameId:2};
const overview={url:'https://mylab.pearson.com/Student/OverviewHomework.aspx?homeworkId=123',tab:{id:10},frameId:2};
const gate={url:'https://mylab.pearson.com/Student/DoHomework.aspx?homeworkId=123',tab:{id:10},frameId:2};
const player={url:'https://mylab.pearson.com/Student/PlayerHomework.aspx?homeworkId=123&questionId=34',tab:{id:11,openerTabId:10,url:'https://mylab.pearson.com/Student/PlayerHomework.aspx?homeworkId=123&questionId=34'},frameId:0};
(async()=>{
  const assignment=(title,key)=>({title,key});
  await assert.rejects(call({type:'pearsonCourseStart',assignments:[assignment('Exam #1','javascript:doHomework(123, false, true)')]},list),/homework or lesson/);
  await assert.rejects(call({type:'pearsonCourseStart',assignments:[assignment('Homework Practice Exam','javascript:doHomework(123, false, true)')]},list),/homework or lesson/);
  await assert.rejects(call({type:'pearsonCourseStart',assignments:[assignment('HW Section 6.2','javascript:WebForm_DoCallback(123)')]},list),/homework or lesson/);
  const firstKey='javascript:doHomework(123, false, true)';
  const secondKey='javascript:doHomework(456, false, true)';
  assert.equal((await call({type:'pearsonCourseStart',assignments:[assignment('Lesson Section 6.1',firstKey),assignment('HW Section 6.2',secondKey)],skippedAssignments:[{title:'Completed lesson',reason:'Already has a score'}],skipReviewPause:true},list)).received,true);
  assert.equal((await call({type:'pearsonCourseList'},list)).title,'Lesson Section 6.1');
  assert.equal((await call({type:'pearsonCourseList'},list)).key,firstKey);
  assert.equal((await call({type:'pearsonCourseOverview',mediaPending:false,questionsPending:true,notStarted:true},{...overview,url:'https://mylab.pearson.com/Student/OverviewHomework.aspx?homeworkId=456'})).received,false,'an unrelated assignment cannot advance the run');
  assert.equal((await call({type:'pearsonCourseOverview',mediaPending:true,questionsPending:true,notStarted:true},overview)).action,'question','media is tracked separately and does not block question work');
  assert.equal((await call({type:'pearsonCourseList'},list)).pendingMediaAssignments[0].assignmentId,'123','media remains linked to the exact assignment for final review');
  assert.equal((await call({type:'pearsonCourseOverview',mediaPending:false,questionsPending:true},overview)).action,'question');
  const ready=await call({type:'pearsonCoursePlayerReady'},player);
  assert.equal(ready.start,true);assert.equal(ready.skipReviewPause,true);
  assert.equal((await call({type:'pearsonCourseQuestionSkipped',questionId:'34',label:'a · Number 1',reason:'Linked data table was unavailable.'},player)).received,true,'course mode records a skipped question for later review');
  assert.equal((await call({type:'pearsonCoursePlayerDone'},player)).received,true);
  assert.equal(sent[0][1].type,'pearsonCourseSave','course runs use Pearson Save, not final submission');
  const savedOverview={url:'https://mylab.pearson.com/Student/OverviewHomework.aspx?homeworkId=123',tab:{id:11,openerTabId:10},frameId:0};
  assert.equal((await call({type:'pearsonCourseOverview',mediaPending:false,questionsPending:true,pendingQuestionIds:['34']},savedOverview)).action,'saved-list','questions logged as skipped can remain unanswered after Save');
  assert.equal((await call({type:'pearsonCourseList'},list)).title,'HW Section 6.2');
  const second={...overview,url:'https://mylab.pearson.com/Student/OverviewHomework.aspx?homeworkId=456'};
  assert.equal((await call({type:'pearsonCourseOverview',mediaPending:false,questionsPending:false,notStarted:true},second)).action,'complete');
  await call({type:'pearsonCourseComplete'},second);
  assert.equal((await call({type:'pearsonCourseOverview',mediaPending:false,questionsPending:false},second)).action,'done');
  const done=await call({type:'pearsonCourseList'},list);
  assert.equal(done.phase,'done');assert.equal(done.skippedQuestions[0].label,'a · Number 1','end-of-run report includes the skipped question location');
  assert.equal(done.skippedAssignments[0].title,'Completed lesson','score-confirmed assignments stay in the end-of-run review summary');
  assert.equal((await call({type:'pearsonCourseStop'},list)).received,true);
  assert.equal((await call({type:'pearsonCourseStart',assignments:[assignment('HW Section1.1-1.6 Introduction',firstKey)]},list)).received,true,'Pearson HW titles without a space are eligible');
  await call({type:'pearsonCourseOverview',mediaPending:false,questionsPending:true,notStarted:true},overview);
  await call({type:'pearsonCoursePlayerReady'},player);
  assert.equal((await call({type:'pearsonCoursePlayerBlocked'},player)).received,true,'Guided mode can stop before any answer is entered');
  assert.equal(stored.pearsonCourse.phase,'attention');
  await call({type:'pearsonCourseStop'},list);
  await call({type:'pearsonCourseStart',assignments:[assignment('Lesson Section 6.2',firstKey)]},list);
  await call({type:'pearsonCourseOverview',mediaPending:false,questionsPending:true,notStarted:true},overview);
  const unskipped={...player,url:'https://mylab.pearson.com/Student/PlayerHomework.aspx?homeworkId=123&questionId=99',tab:{id:11,openerTabId:10,url:'https://mylab.pearson.com/Student/PlayerHomework.aspx?homeworkId=123&questionId=99'}};
  await call({type:'pearsonCoursePlayerReady'},unskipped);await call({type:'pearsonCoursePlayerDone'},unskipped);
  assert.equal((await call({type:'pearsonCourseOverview',mediaPending:false,questionsPending:true,pendingQuestionIds:['99']},{...savedOverview,url:'https://mylab.pearson.com/Student/OverviewHomework.aspx?homeworkId=123'})).action,'attention','unrecorded unanswered work still requires manual attention');
  await call({type:'pearsonCourseStop'},list);
  await call({type:'pearsonCourseStart',assignments:[assignment('Lesson Section 6.1',firstKey)]},list);
  await call({type:'pearsonCourseOverview',mediaPending:false,questionsPending:true,notStarted:true},overview);
  const sameTabPlayer={url:'https://tdx.acs.pearson.com/Player/index.html',tab:{id:10,url:'https://mylab.pearson.com/Student/PlayerHomework.aspx?homeworkId=123'},frameId:0};
  assert.equal((await call({type:'pearsonCoursePlayerReady'},sameTabPlayer)).start,true);
  assert.equal((await call({type:'pearsonCoursePlayerDone'},sameTabPlayer)).received,true);
  const sameTabOverview={url:'https://mylab.pearson.com/Student/OverviewHomework.aspx?homeworkId=123',tab:{id:10,url:'https://mylab.pearson.com/Student/OverviewHomework.aspx?homeworkId=123'},frameId:0};
  assert.equal((await call({type:'pearsonCourseOverview',mediaPending:false,questionsPending:false},sameTabOverview)).action,'saved-list');
  assert.equal(navigated.at(-1)[0],10);
  assert.equal(navigated.at(-1)[1].url,list.url,'after Pearson Save is verified, return to the original assignments list');
  await call({type:'pearsonCourseStop'},list);
  await call({type:'pearsonCourseStart',assignments:[assignment('HW Section 6.1',firstKey),assignment('HW Section 6.2',secondKey)]},list);
  assert.equal((await call({type:'pearsonCourseGate',notStarted:false,canStart:false},gate)).action,'list','past-due gate skips started work');
  assert.equal((await call({type:'pearsonCourseList'},list)).skipped,1);
  assert.equal((await call({type:'pearsonCourseOverview',mediaPending:false,questionsPending:true,notStarted:false},second)).action,'done','started overview is skipped');
  assert.equal((await call({type:'pearsonCourseList'},list)).skipped,2);
  console.log('PASS Pearson course queue, pending-media review and score verification');
})().catch(error=>{console.error(error);process.exitCode=1;});
