'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const version=JSON.parse(fs.readFileSync('manifest.json','utf8')).version;
const read=file=>fs.readFileSync(file,'utf8');
const readme=read('README.md'),changelog=read('CHANGELOG.md'),notes=read('RELEASE-NOTES.md');
const policy=read('VERSIONING.md'),packager=read('scripts/package.py'),publisher=read('scripts/publish-release.py');
assert.match(policy,/MAJOR\.MINOR\.PATCH/,'version policy uses three numeric components');
assert.match(policy,/feature release starts the next series at[\s\S]*`\.0`/,'minor releases begin the next feature series at zero');
assert.match(policy,/GitHub release titled[\s\S]*`Study Assistant MAJOR\.MINOR\.PATCH`/,'the required release title omits the tag prefix');
assert(readme.includes(`Study Assistant — AI Homework Autofill (${version})`),'README heading matches the manifest');
assert(readme.includes(`/releases/download/v${version}/study-assistant-${version}.zip`),'README download URL matches the manifest');
assert(readme.includes(`Study-Assistant-${version}`),'README extracted folder matches the manifest');
assert.match(readme,/\[Versioning and release process\]\(VERSIONING\.md\)/,'README links to the policy');
assert(changelog.includes(`## ${version} —`),'changelog heading matches the manifest');
assert(notes.startsWith(`Study Assistant ${version}`),'release notes title matches the manifest without a v prefix');
assert.match(packager,/folder=f'Study-Assistant-\{version\}'/,'package folder derives from the manifest version');
assert.match(packager,/f'study-assistant-\{version\}\.zip'/,'package ZIP derives from the manifest version');
assert.match(packager,/['"]VERSIONING\.md['"]/,'the ZIP includes the versioning policy linked from its README');
assert.match(publisher,/tag='v'\+version/,'publisher tag derives from the manifest version');
assert.match(publisher,/name':'Study Assistant '\+version/,'GitHub release title derives from the manifest version without the v prefix');
console.log('PASS MAJOR.MINOR.PATCH policy and synchronized release artifacts');
